Feature/movies/details/episodes
ERGataullin/AniWay pull request #143
Opened 2024-09-21 08:47 UTC by KAPLMARKS

2024-09-21 10:20 UTC, ERGataullin requested changes

2024-09-21 10:20 UTC, ERGataullin commented on .fvm/fvm_config.json
Опять ты этот файл рудиментный сюда тащишь :(

2024-09-21 10:20 UTC, ERGataullin commented on .vscode/settings.json
И снова верни запятые
Почему они у тебя убираются каждый раз?

2024-09-21 10:20 UTC, ERGataullin commented on core/lib/src/domain/models/proxied_uri.dart
>    }
Верни как было

2024-09-21 10:20 UTC, ERGataullin commented on features/common/movies/lib/src/data/sources/anime365.dart
> +        anime365Data['episodes'] != null
Зачем через отрицание? Тем более у тебя так короткий ответ (`const []`) прячется в попу, а ведь читабельнее вариант `condition ? const [] : махинамахинамахинамахинамахинамахина`

2024-09-21 10:20 UTC, ERGataullin commented on features/common/movies/lib/src/data/sources/anime365.dart
> +                  if (previewUrl?.startsWith('//') ?? false) {
Убери фигурки, если в 1 строчку влезет

2024-09-21 10:20 UTC, ERGataullin commented on features/common/movies/lib/src/presentation/episodes/model.dart
> +    movie.dispose();
Где диспоуз `loading`'а?

2024-09-21 10:20 UTC, ERGataullin commented on features/common/movies/lib/src/presentation/episodes/widget.dart
> +    childAspectRatio: 13 / 9,
Почему выбрал такое странное соотношение? Может лучше 16/9? Типо стандартное соотношения для видео, соотв-но и превьюшки будут в 16/9 почти всегда

2024-09-21 10:20 UTC, ERGataullin commented on features/common/movies/lib/src/presentation/episodes/widget.dart
> +            ? const Center(
А почему `Scaffold` с `AppBar`'ом не отображаем во время загрузки? Из-за этого не понятно что за страница (т.к. заголовка нет) и кнопка назад отсутствует

2024-09-21 10:20 UTC, ERGataullin commented on features/common/movies/lib/src/presentation/episodes/widget.dart
> +            context.l10n.movieEpisode(data.type.name, data.number ?? 0),
Всё-таки давай вынесем это в WM, не место ему тут
Добавь в WM функцию `String getEpisodeTitle(EpisodeData episode)`

2024-09-21 10:20 UTC, ERGataullin commented on features/common/movies/lib/src/presentation/episodes/wm.dart
> +        final startIndex = index * _groupSize;
Ни к чему тут высчитывать всё то же, что и в `tabsEpisodes`
Лучше сделай триггером `tabsEpisodes` и тело такое:
```
final List<EpisodeData> tabEpisodes = tabsEpisodes[index];
return '${tabEpisodes.first.number}-'
            '${tabEpisodes.last.number}';
```

2024-09-21 10:20 UTC, ERGataullin commented on features/common/movies/lib/src/presentation/episodes/wm.dart
> +  ValueListenable<List<List<EpisodeData>>> get tabEpisodes;
Заренейм в `tabsEpisodes`

2024-09-21 10:20 UTC, ERGataullin commented on features/common/movies/lib/src/presentation/episodes/wm.dart
> +  ValueListenable<List<List<EpisodeData>>> get tabEpisodes;
А то как-будто это эпизоды одной конкретной табы

2024-09-21 10:20 UTC, ERGataullin commented on features/common/movies/lib/src/presentation/episodes/wm.dart
> +        return '${episodes.value[startIndex].number}-'
Лучше в l10n запихнуть

2024-09-21 10:20 UTC, ERGataullin commented on features/common/movies/lib/src/presentation/episodes/wm.dart
> +  ValueListenable<List<EpisodeData>> get episodes;
А это где-то используется вообще? У тебя же, по-идее, только `tabsEpisodes` должны юзаться

2024-09-21 10:20 UTC, ERGataullin commented on features/common/movies/lib/src/presentation/episodes/wm.dart
> +    super.dispose();
Недостающие диспоузы добавь

2024-09-21 10:20 UTC, ERGataullin commented on features/common/movies/lib/src/presentation/movie/widget.dart
> +  final void Function() onEpisodesPressed;
`VoidCallback` вместо `void Function()`

2024-09-21 10:20 UTC, ERGataullin commented on features/common/movies/lib/src/presentation/movie/widget.dart
> +              context.l10n.movieEpisode(data.type.name, data.number ?? 0),
Точно так же вынести в WM

2024-09-21 10:20 UTC, ERGataullin commented on features/common/movies/lib/src/presentation/movie/wm.dart
> +        model.movie.value!.episodes.length > 1,
Просто `model.movie.value?.episodes.isNotEmpty ?? false`

2024-09-21 10:20 UTC, ERGataullin commented on features/common/movies/lib/src/presentation/movie/wm.dart
> +  late final DynamicData<bool> showEpisodes = DynamicData(
Го её переместим над `episodesLabel`

2024-09-21 10:42 UTC, KAPLMARKS commented on features/common/movies/lib/src/presentation/episodes/widget.dart
> +    childAspectRatio: 13 / 9,
некрасиво выглядит с 16/9

2024-09-21 10:43 UTC, KAPLMARKS commented on features/common/movies/lib/src/presentation/episodes/widget.dart
> +            ? const Center(
PreferredSize Widget требует

2024-09-21 10:52 UTC, KAPLMARKS commented on features/common/movies/lib/src/presentation/episodes/wm.dart
> +  ValueListenable<List<EpisodeData>> get episodes;
episodes в других методах используются

2024-09-21 14:24 UTC, ERGataullin requested changes

2024-09-21 14:24 UTC, ERGataullin commented on .fvm/fvm_config.json
Почему пометил как "разрешённое" (resolved), хотя файл остался =_=

2024-09-21 14:24 UTC, ERGataullin commented on .vscode/settings.json
И тут пометил как resolved, хотя нифига не resolved

2024-09-21 14:24 UTC, ERGataullin commented on .vscode/settings.json
> +  "dart.flutterSdkPath": ".fvm/versions/3.24.1"
Наверх передвинь, чтобы по алфавиту было

2024-09-21 14:24 UTC, ERGataullin commented on core/lib/src/domain/models/proxied_uri.dart
>    }
И тут resolved, хотя нифига не resolved =_=

2024-09-21 14:24 UTC, ERGataullin commented on features/common/movies/lib/src/data/sources/anime365.dart
> +        anime365Data['episodes'] != null
Снова resolved, хотя не resolved
Я не понимаю, что за прикол?
Может ты коммит залить забыл
И вообще, помечать как resolved должен, разумеется, ревьюер
Если ты считаешь, что оно resolved, то ты должен убедить в этом ревьюера и тогда он уже проставит resolved

2024-09-21 14:24 UTC, ERGataullin commented on features/common/movies/lib/src/data/sources/anime365.dart
> +        anime365Data['episodes'] != null
Я хз как ревьюить, тут слишком много нерезолвнутых резолвдов

2024-09-25 19:55 UTC, ERGataullin requested changes

2024-09-25 19:55 UTC, ERGataullin commented on .vscode/settings.json
> +  "dart.flutterSdkPath": ".fvm/versions/3.24.1"
Не передвинул

2024-09-25 19:55 UTC, ERGataullin commented on features/common/movies/lib/src/presentation/episodes/widget.dart
> +  static const SliverGridDelegateWithMaxCrossAxisExtent gridDelegate =
Запривать

2024-09-25 19:55 UTC, ERGataullin commented on features/common/movies/lib/src/presentation/episodes/widget.dart
> +            bottom: wm.showLoader.value
Тут лучше тогда не на `showLoader.value` смотреть, а на `tabController.value != null`
Соотв-но, `wm.showLoader` убрать с 38 строки, вместо этого обернув `body` в более узкий `ListenableBuilder`

2024-09-25 19:55 UTC, ERGataullin commented on features/common/movies/lib/src/presentation/episodes/widget.dart
> +                            gridDelegate: EpisodesWidget.gridDelegate,
Зачем `EpisodesWidget.gridDelegate`, просто `gridDelegate`
Да и вообще, зачем этот `gridDelegate` на уровне класса, убери ту переменную и пусть прямо тут создаётся

2024-09-25 19:55 UTC, ERGataullin commented on features/common/movies/lib/src/presentation/episodes/wm.dart
> +        final endIndex = math.min(
У нас же тип обязательный при объявлении, не?

2024-09-25 19:55 UTC, ERGataullin commented on features/common/movies/lib/src/presentation/episodes/wm.dart
> +        .movieEpisode(episodeData.type.name, episodeData.number ?? 0);
Запятую для нормального переноса

2024-09-25 19:55 UTC, ERGataullin commented on features/common/movies/lib/src/presentation/episodes/wm.dart
> +    _episodes.dispose();
Приватную на самый верх двинь, плз

2024-09-25 19:55 UTC, ERGataullin commented on features/common/movies/lib/src/presentation/movie/widget.dart
> +                aspectRatio: 16 / 9,
Из-за того, что тут `AspectRatio`, при некоторых настройках системы текст не будет влезать даже по высоте, будет overflow
Нужно обойтись тут без этого второго `AspectRatio` (первый - на уровне грида)

2024-09-25 19:55 UTC, ERGataullin commented on features/common/movies/lib/src/presentation/movie/wm.dart
> +    showEpisodes.dispose();
Двинь на 1 строку вверх
Мой тупой перфекционизм, чтобы было в порядке объявления

2024-09-25 19:55 UTC, ERGataullin commented on features/shared/l10n/assets/ru.arb
> +    "tabEpisodesText": "{firstEpisode}-{lastEpisode}",
`episodesRangeShort` назови
В крайнем случае должно было быть `episodesTabText`

2024-09-25 19:55 UTC, ERGataullin commented on features/shared/l10n/assets/ru.arb
> +            "firstEpisode": {
Заренеймь их в `start` и `end`, чтобы подходило по смысле к range

2024-09-25 19:55 UTC, ERGataullin commented on features/shared/l10n/assets/ru.arb
> +    "tabEpisodesText": "{firstEpisode}-{lastEpisode}",
Хотя лучше даже просто `range`

2024-10-12 19:14 UTC, KAPLMARKS commented on features/common/movies/lib/src/presentation/movie/widget.dart
> +                aspectRatio: 16 / 9,
ПЕРЕПУТАЛ ЭДГААААР!!!😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡😡

2024-10-12 19:29 UTC, ERGataullin approved these changes

2024-10-12 19:29 UTC, merged