Movies details play button without arrived episodes fix
ERGataullin/AniWay pull request #144
Opened 2024-10-16 15:44 UTC by KAPLMARKS

2024-10-16 15:45 UTC, KAPLMARKS commented
Тайтл для проверки Одинокий герой

2024-10-16 21:22 UTC, ERGataullin requested changes

2024-10-16 21:22 UTC, ERGataullin commented on features/common/movies/lib/src/presentation/movie/widget.dart
> +              : wm.episodes.value.isEmpty
Марат, что за корявый тернарник где у тебя просто двойное условие с 2 двумя вариантами?
`wm.showLoader.value || wm.episodes.value.isEmpty ? null : const _PlayButton()`

2024-10-16 21:23 UTC, ERGataullin commented on features/common/movies/lib/src/presentation/movie/widget.dart
> +              : wm.episodes.value.isEmpty
Плюс это условие должно определяться в WM, а не в виджете
Так что в WM добавляем `ValueListenable<bool> get showPlayButton`

2024-10-16 21:24 UTC, ERGataullin commented
Шаблон наименования МРа ты совсем забыл, я так понимаю :(

2024-10-17 09:21 UTC, ERGataullin requested changes

2024-10-17 09:21 UTC, ERGataullin commented on features/common/movies/lib/src/presentation/movie/widget.dart
> +          floatingActionButton: wm.showPlayButton.value ? null : _PlayButton(),
`const` вставь, плз

2024-10-17 09:21 UTC, ERGataullin commented on features/common/movies/lib/src/presentation/movie/wm.dart
> +  ValueListenable<bool> get showPlayButton {
Вау-вау, это ты что за костыль такой придумал?
Го нормально через `DynamicData`, как мы и делали?

2024-10-17 10:11 UTC, KAPLMARKS commented on features/common/movies/lib/src/presentation/movie/wm.dart
> +  ValueListenable<bool> get showPlayButton {
я триггер не знал какой вставить

2024-10-17 11:02 UTC, ERGataullin commented on features/common/movies/lib/src/presentation/movie/wm.dart
> +  ValueListenable<bool> get showPlayButton {
Как же, у тебя условие, которое ты изначально в виджете делал, было правильным
Соотв-но, триггером должны быть участники того условия, а именно `showLoader` и `episodes`

2024-11-02 17:00 UTC, ERGataullin requested changes

2024-11-02 17:00 UTC, ERGataullin commented on features/common/movies/lib/src/presentation/movie/widget.dart
> +          floatingActionButton: wm.showPlayButton.value ? null : _PlayButton(),
Так и не появился `const`.... ==__==

2024-11-02 17:00 UTC, ERGataullin commented on features/common/movies/lib/src/presentation/movie/wm.dart
> +  ValueListenable<bool> get showPlayButton {
Как была какая-то херь, так и осталась...........

2024-11-02 17:00 UTC, ERGataullin commented on features/common/movies/lib/src/presentation/movie/wm.dart
> +  ValueListenable<bool> get showPlayButton {
Плюс не диспоузишь

2024-11-02 17:07 UTC, ERGataullin requested changes

2024-11-02 17:07 UTC, ERGataullin commented on features/common/movies/lib/src/presentation/movie/widget.dart
> +          floatingActionButton: wm.showPlayButton.value ? null : _PlayButton(),
Так и не появился `const` x2... Да это же комбо!
Ещё и условие неправильное, кстати... У тебя получается: "Показывать кнопку просмотра, когда `showPlayButton.value == false`"

2024-11-02 17:07 UTC, ERGataullin commented on features/common/movies/lib/src/presentation/movie/wm.dart
> +    () => showLoader.value || !showEpisodes.value,
А почему ты говоришь: "Показывать кнопку просмотра", когда у тебя идёт загрузка или нет эпизодов?

2024-11-02 17:08 UTC, ERGataullin commented
@KAPLMARKS, ещё и пайплайн упал
<img width="1414" alt="{380B2258-B4FB-41D9-A482-3419AFE5A360}" src="https://github.com/user-attachments/assets/ef68be51-2517-46b1-a2b9-e25e1cab9ea0">

2024-11-02 17:39 UTC, ERGataullin requested changes

2024-11-02 17:39 UTC, ERGataullin commented on features/common/movies/lib/src/presentation/movie/widget.dart
> +  const _PlayButton();
Пустую строку между конструктором и функцией

2024-11-02 17:39 UTC, ERGataullin commented on features/common/movies/lib/src/presentation/movie/wm.dart
> +    () => !showLoader.value || showEpisodes.value,
Условие неверное
Подумай

2024-11-02 17:41 UTC, ERGataullin commented on features/common/movies/lib/src/presentation/movie/wm.dart
> +    () => !showLoader.value || showEpisodes.value,
Должно быть умножение

2024-11-02 17:52 UTC, ERGataullin approved these changes

2024-11-02 17:54 UTC, merged