Movies details poster height fix
ERGataullin/AniWay pull request #145
Opened 2024-11-06 18:39 UTC by KAPLMARKS

2024-11-06 18:44 UTC, ERGataullin requested changes

2024-11-06 18:44 UTC, ERGataullin commented on features/common/movies/lib/src/presentation/movie/widget.dart
> +            : MediaQuery.of(context).size.width * .95,
1. Что оно забыло в виджете?
2. Давай через соотношение сторон. Нужен прямоугольник с высотой > ширины (потому что у постеров, але, высота > ширины, чего ты высоту ещё меньше ширины вдруг делаешь-то)

2024-11-06 18:53 UTC, KAPLMARKS commented on features/common/movies/lib/src/presentation/movie/widget.dart
> +            : MediaQuery.of(context).size.width * .95,
1.Так, я понял MediaQuery перенести в wm
2. Непон, мне надо  63/60 * MediaQuery.of(context).size.width??? или использовать AspectRatio как-то?

2024-11-06 18:59 UTC, ERGataullin commented on features/common/movies/lib/src/presentation/movie/widget.dart
> +            : MediaQuery.of(context).size.width * .95,
1. Не `MediaQuery`, а весь `DynamicData<double> posterHeight`, и обновлять в `didChangeDependencies()`
2. Да, примерно так. `MediaQuery.of(context).size.width * 16 / 9`, например. Но поменьше, может `12 / 9`. Лучше попробуй варианты и покидай скриншоты, вместе решим

2024-11-23 17:34 UTC, ERGataullin requested changes

2024-11-23 17:34 UTC, ERGataullin commented on features/common/movies/lib/src/presentation/movie/widget.dart
>        listenable: context.wm.showLoader,
Нам тут не важно `showLoader` или нет, важно только `posterHeight` слушать

2024-11-23 17:34 UTC, ERGataullin commented on features/common/movies/lib/src/presentation/movie/wm.dart
> +  late final DynamicData<double?> posterHeight = DynamicData(
Где вызов `posterHeight.update()` в `didChangeDependencies()`? У тебя же не обновляется значение при изменении `MediaQuery` (например, когда браузер ресайзишь)

2024-11-23 17:48 UTC, ERGataullin approved these changes

2024-11-23 17:50 UTC, merged