Movies parsing fix
ERGataullin/AniWay pull request #21
Opened 2024-02-04 12:27 UTC by KAPLMARKS

2024-02-04 13:25 UTC, ERGataullin requested changes

2024-02-04 13:25 UTC, ERGataullin commented on modules/movies/lib/src/data/sources/anime365.dart
> +          r'^Проморолик$'
Отформать файл
Тут либо не должно быть переноса строки, либо должна быть запятая

2024-02-05 16:50 UTC, KAPLMARKS commented on modules/movies/lib/src/data/sources/anime365.dart
> +          r'^Проморолик$'
Запятую добавил

2024-02-05 17:12 UTC, ERGataullin commented on modules/movies/lib/src/data/sources/anime365.dart
> +          r'^Проморолик$'
А в одну строчку разве не помещается?
65-70 символов насчитал, а лимит - 80

2024-02-06 17:39 UTC, ERGataullin commented on modules/movies/lib/src/domain/models/movie_episode.dart
> +  pv,
Необходимо добавить значение "Промо" в ru.arb под ключом moviePreviewType

2024-02-06 17:40 UTC, ERGataullin commented on modules/movies/lib/src/domain/models/movie_type.dart
> +  pv,
Необходимо добавить значение "Промо" в ru.arb под ключом moviePreviewType

2024-02-06 18:03 UTC, ERGataullin approved these changes

2024-02-06 18:03 UTC, merged